# -- Main Menu --

[[main]]
  name = "About"
  pageRef = "about"
  weight = 10

[[main]]
  name = "Tools"
  pageRef = "tools"
  weight = 20

[[main]]
  name = "Infrastructure"
  pageRef = "infrastructure"
  weight = 30

[[main]]
  name = "Concepts"
  pageRef = "concepts"
  weight = 40

[[main]]
  name = "GitHub"
  url = "https://github.com/con/serve"
  weight = 50
  [main.params]
    icon = "github"
    showName = false
    target = "_blank"

[[main]]
  identifier = "search"
  weight = 99
  [main.params]
    action = "search"

# -- Footer Menu --

[[footer]]
  name = "Tags"
  pageRef = "tags"
  weight = 10

[[footer]]
  name = "Categories"
  pageRef = "categories"
  weight = 20

[[footer]]
  name = "Media Types"
  pageRef = "media_types"
  weight = 30

[[footer]]
  name = "Integrations"
  pageRef = "integrations"
  weight = 40

[[footer]]
  name = "AI Readiness"
  pageRef = "ai_readiness"
  weight = 50
